services:
  angular-app:
    image: iltavo/pwu-node:v1
    container_name: pwu
    build:
      context: /
      dockerfile: Dockerfile # Assicurati di avere un Dockerfile nell'app Angular
    ports:
      - "8081:8081" # Espone la porta 4200 dell'app Angular all'host
    depends_on:
      - db
    networks:
      - my_bridge_network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: pwu # Nome del database
      POSTGRES_USER: pwu # Username per il database
      POSTGRES_PASSWORD: valery18 # Password per l'accesso al database
    ports:
      - "1486:5432" # Espone la porta 5432 del database all'host
    volumes:
      - postgres-data:/var/lib/postgresql/data # Mantiene i dati del database tra i riavvii del container
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Script inizializzazione
    networks:
      - my_bridge_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: valerio.tavoletti@gmail.com
      PGADMIN_DEFAULT_PASSWORD: valery18
    ports:
      - "5050:80" # Espone PgAdmin sulla porta 5050 all'host
    depends_on:
      - db
    networks:
      - my_bridge_network

volumes:
  postgres-data:
    driver: local

networks:
  my_bridge_network:
    driver: bridge
